[package]
name    = "saa-macros"
edition = { workspace = true }
authors = { workspace = true }
version = { workspace = true }

[dependencies]
macros-proto        = { path = "../macros-proto" }

# Substrate
scale               = { workspace = true }
scale-info          = { workspace = true }
# CosmWasm
cosmwasm-schema     = { workspace = true }
# Solana
borsh               = { workspace = true }


[features]
default        = []
substrate      = []
cosmwasm       = []
solana         = []

