[package]
name    = "saa-macros"
edition = { workspace = true }
authors = { workspace = true }
version = { workspace = true }

[dependencies]
macros-proto = { path = "../macros-proto" }

[features]
default        = []
substrate      = []
cosmwasm       = []
solana         = []

