[package]
name = "saa-custom"
edition = { workspace = true }
authors = { workspace = true }
version = { workspace = true }


[dependencies]
hex                     = { workspace = true }
k256                    = { workspace = true }
bech32                  = { workspace = true }
base64                  = { workspace = true }

saa-common              = { workspace = true }
saa-schema              = { workspace = true }

cosmwasm-std            = { workspace = true, optional = true }

scale                   = { workspace = true, optional = true }
scale-info              = { workspace = true, optional = true }

borsh                   = { workspace = true, optional = true }
schemars                = { workspace = true, optional = true }
serde                   = { workspace = true, optional = true }


[features]
default = ["std"]
solana = [
    "dep:borsh",
    "saa-schema/solana",
    "saa-common/solana",
]
substrate = [
    "dep:scale",
    "dep:scale-info",
    "saa-schema/substrate",
    "saa-common/substrate",
]
cosmwasm = [
    "dep:cosmwasm-std",
    "dep:schemars",
    "dep:serde",
    "saa-schema/cosmwasm",
    "saa-common/cosmwasm",
]
std = [
    "scale?/std",
    "scale-info?/std",
    "bech32/std",
    "saa-schema/std",
    "saa-common/std",
]


