[package]
name        = "saa-custom"
description = "Custom credentials built on top of curves and their verification logic for smart account auth"
edition     = { workspace = true }
authors     = { workspace = true }
version     = { workspace = true }
license     = { workspace = true }
repository  = { workspace = true }

[dependencies]
hex                     = "0.4.3"
sha2                    = { workspace = true } 
bech32                  = { workspace = true }
base64                  = { workspace = true }

saa-common              = { workspace = true }
saa-schema              = { workspace = true }
saa-curves              = { workspace = true }

scale                   = { workspace = true, optional = true }
scale-info              = { workspace = true, optional = true }

borsh                   = { workspace = true, optional = true }
schemars                = { workspace = true, optional = true }
serde                   = { workspace = true }

[dev-dependencies]
cosmwasm-std            = { workspace = true }
secretwasm-std          = { workspace = true }


[features]
default = [
    "std", "replay"
]
solana = [
    "dep:borsh",
    "saa-schema/solana",
    "saa-common/solana",
    "saa-curves/solana",
]
substrate = [
    "dep:scale",
    "dep:scale-info",
    "saa-schema/substrate",
    "saa-common/substrate",
    "saa-curves/substrate",
]
cosmwasm = [
    "dep:schemars",
    "saa-schema/cosmwasm",
    "saa-common/cosmwasm",
    "saa-curves/cosmwasm",
    "wasm"
]
std = [
    "scale?/std",
    "scale-info?/std",
    "bech32/std",
    "saa-schema/std",
    "saa-common/std",
    "saa-curves/std",
]
native = [
    "saa-common/native",
    "saa-curves/native",
]
injective = [
    "saa-common/injective",
]
replay = [
    "storage",
    "saa-common/replay"
]
storage = [
    "saa-common/storage"
]
cosmwasm_2_1 = [
    "saa-common/cosmwasm_2_1",
    "cosmwasm",
]
secretwasm = [
    "saa-common/secretwasm",
    "saa-curves/secretwasm",
    "wasm"
]
wasm = []