[package]
name = "saa-custom"
edition = { workspace = true }
authors = { workspace = true }
version = { workspace = true }


[dependencies]
hex                     = "0.4.3"
sha2                    = { workspace = true } 
bech32                  = { workspace = true }
base64                  = { workspace = true }

saa-common              = { workspace = true }
saa-schema              = { workspace = true }
saa-curves              = { workspace = true }

cosmwasm-std            = { workspace = true, optional = true }

scale                   = { workspace = true, optional = true }
scale-info              = { workspace = true, optional = true }

borsh                   = { workspace = true, optional = true }
schemars                = { workspace = true, optional = true }
serde                   = { workspace = true }



[features]
default = [
    "std", "cosmwasm"
]
solana = [
    "dep:borsh",
    "saa-schema/solana",
    "saa-common/solana",
    "saa-curves/solana",
]
substrate = [
    "dep:scale",
    "dep:scale-info",
    "saa-schema/substrate",
    "saa-common/substrate",
    "saa-curves/substrate",
]
cosmwasm = [
    "dep:cosmwasm-std",
    "dep:schemars",
    "saa-schema/cosmwasm",
    "saa-common/cosmwasm",
    "saa-curves/cosmwasm",
]
std = [
    "scale?/std",
    "scale-info?/std",
    "bech32/std",
    "saa-schema/std",
    "saa-common/std",
    "saa-curves/std",
]
native = [
    "saa-common/native",
    "saa-curves/native",
]

