[package]
name = "saa-custom"
edition = { workspace = true }
authors = { workspace = true }
version = { workspace = true }


[dependencies]
hex                     = { workspace = true }
k256                    = { workspace = true }
bech32                  = { workspace = true }
data-encoding           = { workspace = true }

saa-common              = { workspace = true }
saa-schema              = { workspace = true }


[features]
default     = []
cosmwasm    = []
