[workspace]
members = [
    "packages/*",
]

resolver = "2"

[workspace.package]
version         = "0.0.1"
edition         = "2021"
repository      = "https://github.com/MegaRockLabs/smart-account-auth"
authors         = [ "Kromsten <kromsten@megarock.labs>" ]


[workspace.dependencies]
k256                    = { version = "0.13.3", default-features = false, features = ["ecdsa"] }
hex                     = { version = "0.4.3"  }
bech32                  = { version = "0.9.1"  }


semver                  = "1.0.21"
thiserror               = "1.0.56"

saa-evm                 = { path = "packages/evm" }
saa-common              = { path = "packages/common" }
saa-bundle              = { path = "packages/bundle" }
saa-macros              = { path = "packages/macros" }

cosmwasm-std            = { version = "1.5.1", default-features = false }
cosmwasm-crypto         = { version = "1.5.1", default-features = false }
cw-utils                = { version = "1.0.3", default-features = false }



# Substrate
scale               = { version = "3.6.9", package = "parity-scale-codec", default-features = false, features = ["derive"] }
scale-info          = { version = "2.10.0", default-features = false, features = ["derive"] }
# CosmWasm
cosmwasm-schema      = "1.4.1"
schemars             = "0.8.16"
serde                = "1.0.195"
# Solana
borsh                = "1.3.1"
borsh-derive         = "1.3.1"


[profile.release]
rpath            = false
lto              = true
overflow-checks  = true
opt-level        = 3
debug            = false
debug-assertions = false
