[workspace]
members = [
    "packages/*",
]

resolver = "2"

[workspace.package]
version         = "0.3.1"
edition         = "2021"
repository      = "https://github.com/MegaRockLabs/smart-account-auth"
description     = "Utilities, types and verification logic for smart contract / program based accounts for various blockchain-based virtual machines"
authors         = [ "Kromsten <kromsten@megarock.labs>" ]


[workspace.dependencies]
k256                    = { version = "0.13.3", default-features = false, features = ["ecdsa"] }
ed25519-zebra           = { version = "4.0.3",  default-features = false }
digest                  = { version = "0.10.7", default-features = false }

hex                     = { version = "0.4.3",  default-features = false }
data-encoding           = { version = "2.5.0",  default-features = false }
bech32                  = { version = "0.9.1",  default-features = false }
base64                  = { version = "0.21.7", default-features = false }


semver                  = { version = "1.0.21", default-features = false }
thiserror               = { version = "1.0.21", default-features = false }

saa-custom              = { path = "packages/custom" }
saa-common              = { path = "packages/common" }
saa-bundle              = { path = "packages/bundle" }
saa-schema              = { path = "packages/schema" }
saa-curves              = { path = "packages/curves" }


cosmwasm-std            = { version = "1.5.2", default-features = false }
cosmwasm-crypto         = { version = "1.5.2", default-features = false }
cw-utils                = { version = "1.0.3", default-features = false }


# Substrate
scale               = { version = "3.6.9", package = "parity-scale-codec", default-features = false }
scale-info          = { version = "2.10.0", default-features = false }
ink                 = { version = "4.3.0",  default-features = false}
# CosmWasm
serde                = { version = "1.0.196", default-features = false, features = ["derive"] }
schemars             = { version = "0.8.16",  default-features = false }
# Solana
borsh               = { version = "1.3.1", default-features = false, features = ["derive"] }




[profile.release]
rpath            = false
lto              = true
overflow-checks  = true
opt-level        = 3
debug            = false
debug-assertions = false