[workspace]
members = [
    "packages/*",
]

resolver = "2"

[workspace.package]
version         = "0.2.0"
edition         = "2021"
repository      = "https://github.com/MegaRockLabs/smart-account-auth"
description     = "Utilities, types and verification logic for smart contract / program based accounts for various blockchain-based virtual machines"
authors         = [ "Kromsten <kromsten@megarock.labs>" ]



[workspace.dependencies]
k256                    = { version = "0.13.3", default-features = false, features = ["ecdsa"] }
hex                     = { version = "0.4.3"  }
bech32                  = { version = "0.9.1"  }
data-encoding           = { version = "2.5.0"  }

semver                  = "1.0.21"
thiserror               = "1.0.56"

saa-custom              = { path = "packages/custom" }
saa-common              = { path = "packages/common" }
saa-bundle              = { path = "packages/bundle" }
saa-schema              = { path = "packages/schema" }
saa-curves              = { path = "packages/curves" }


cosmwasm-std            = { version = "1.5.2", default-features = false }
cosmwasm-crypto         = { version = "1.5.2", default-features = false }
cw-utils                = { version = "1.0.3", default-features = false }

cosmwasm-schema     = { version = "1.5.2" }

# Substrate
scale               = { version = "3.6.9", package = "parity-scale-codec" }
scale-info          = { version = "2.10.0"  }
# CosmWasm
schemars             = "0.8.16"
serde                = "1.0.195"
# Solana

borsh               = { version = "1.3.1", features = ["derive"] }


[profile.release]
rpath            = false
lto              = true
overflow-checks  = true
opt-level        = 3
debug            = false
debug-assertions = false
