[workspace]
members = [
    "packages/*",
]

resolver = "2"

[workspace.package]
version         = "0.4.5"
edition         = "2021"
repository      = "https://github.com/MegaRockLabs/smart-account-auth"
description     = "Utilities, types and verification logic for smart contract / program based accounts for various blockchain-based virtual machines"
authors         = [ "Kromsten <kromsten@megarock.labs>" ]


[workspace.dependencies]
k256                    = { version = "0.13.3", default-features = false, features = ["ecdsa"] }

hex                     = { version = "0.4.3",  default-features = false }
data-encoding           = { version = "2.5.0",  default-features = false }
bech32                  = { version = "0.11.0", default-features = false, features = ["alloc"] }
base64                  = { version = "0.22.0", default-features = false, features = ["alloc"] }


semver                  = { version = "1.0.21", default-features = false }
thiserror               = { version = "1.0.21", default-features = false }

smart-account-auth      = { path = "packages/bundle" }
saa-custom              = { path = "packages/custom" }
saa-common              = { path = "packages/common" }
saa-schema              = { path = "packages/schema" }
saa-curves              = { path = "packages/curves" }


cosmwasm-crypto         = { version = "2.0.1", default-features = false }
cosmwasm-std            = { version = "2.0.1", default-features = false }
getrandom               = { version = "0.2.3",  default-features = false, features = ["custom"] }

# Substrate
scale               = { version = "3.6.9", default-features = false, features = ["derive"], package = "parity-scale-codec"}
scale-info          = { version = "2.10.0", default-features = false, features = ["derive"] }
ink                 = { version = "5.0.0",  default-features = false }

# CosmWasm
serde                = { version = "1.0.197", default-features = false, features = ["derive"] }
schemars             = { version = "0.8.16",  default-features = false, features = ["derive"] }
# Solana
borsh               = { version = "1.4.0", default-features = false, features = ["derive"] }




[profile.release]
rpath            = false
lto              = true
overflow-checks  = true
opt-level        = 3
debug            = false
debug-assertions = false