[workspace]
members = [
    "packages/*",
]

resolver = "2"

[workspace.package]
version         = "0.4.6"
edition         = "2021"
repository      = "https://github.com/MegaRockLabs/smart-account-auth"
description     = "Utilities, types and verification logic for smart contract / program based accounts for various blockchain-based virtual machines"
authors         = [ "Kromsten <kromsten@megarock.labs>" ]


[workspace.dependencies]
k256                    = { version = "0.13.1", default-features = false, features = ["ecdsa"] }

hex                     = { version = "0.4.3",  default-features = false }
data-encoding           = { version = "2.6.0",  default-features = false }
bech32                  = { version = "0.11.0", default-features = false, features = ["alloc"] }
base64                  = { version = "0.22.1", default-features = false, features = ["alloc"] }


semver                  = { version = "1.0.22", default-features = false }
thiserror               = { version = "1.0.59", default-features = false }

smart-account-auth      = { path = "packages/bundle" }
saa-custom              = { path = "packages/custom" }
saa-common              = { path = "packages/common" }
saa-schema              = { path = "packages/schema" }
saa-curves              = { path = "packages/curves" }


cosmwasm-crypto         = { version = "1.5.4", default-features = false }
cosmwasm-std            = { version = "1.5.4", default-features = false }
getrandom               = { version = "0.2.14",  default-features = false, features = ["custom"] }

# Substrate
scale               = { version = "3.6.9", default-features = false, features = ["derive"], package = "parity-scale-codec"}
scale-info          = { version = "2.10.2", default-features = false, features = ["derive"] }
ink                 = { version = "5.0.0",  default-features = false }
# CosmWasm
serde                = { version = "1.0.197", default-features = false, features = ["derive"] }
schemars             = { version = "0.8.16",  default-features = false, features = ["derive"] }
# Solana
borsh               = { version = "1.4.0", default-features = false, features = ["derive"] }



[profile.release.package.smart-account-auth]
codegen-units = 1
incremental = false


[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false