[package]
name    = "macros-proto"
edition = { workspace = true }
authors = { workspace = true }
version = { workspace = true }

[lib]
proc-macro = true

[dependencies.proc-macro2]
version = "1"

[dependencies.quote]
version = "1"

[dependencies.syn]
version = "1"
features = [
    "full",
    "printing",
    "extra-traits",
]

[features]
default        = []
substrate      = []
cosmwasm       = []
solana         = []
