[package]
name    = "macros-proto"
edition = { workspace = true }
authors = { workspace = true }
version = { workspace = true }

[lib]
doctest    = false # disable doc tests
proc-macro = true

[dependencies]
proc-macro2    = "1.0.76"
quote          = "1.0.35"
syn            = "1"

[features]
default        = []
substrate      = []
cosmwasm       = []
solana         = []

