[package]
name    = "saa-schema"
description = "Macros and serialization utlities for various blockchain based virtual machines"
edition = { workspace = true }
authors = { workspace = true }
version = { workspace = true }
license = { workspace = true }

[dependencies]
macros-proto        = { path = "../macros-proto", version = "0.12.0", package = "saa-macros-proto" }

# Substrate
scale               = { workspace = true, default-features = false, features = ["derive"], optional = true }
scale-info          = { workspace = true, default-features = false, features = ["derive"], optional = true }
# CosmWasm
serde               = { workspace = true, default-features = false, features = ["derive"], optional = true }
schemars            = { workspace = true, default-features = false, features = ["derive"], optional = true }
# Solana
borsh               = { workspace = true, default-features = false, features = ["derive"], optional = true }


[features]
default        = ["std"]
std            = [
    "scale?/std", 
    "scale-info?/std", 
]
solana         = ["dep:borsh",                   "macros-proto/solana"    ]
substrate      = ["dep:scale", "dep:scale-info", "macros-proto/substrate" ]
cosmwasm       = ["dep:serde", "dep:schemars",   "macros-proto/cosmwasm"  ]