[package]
name    = "saa-schema"
edition = { workspace = true }
authors = { workspace = true }
version = { workspace = true }

[dependencies]
macros-proto        = { path = "../macros-proto" }

# Substrate
scale               = { workspace = true, default-features = false, features = ["derive"], optional = true }
scale-info          = { workspace = true, default-features = false, features = ["derive"], optional = true }
# CosmWasm
serde               = { workspace = true, default-features = false, features = ["derive"], optional = true }
schemars            = { workspace = true, default-features = false, features = ["derive"], optional = true }
# Solana
borsh               = { workspace = true, default-features = false, features = ["derive"], optional = true }



[features]
default        = []
std            = [
    "dep:scale-info", 
    "dep:scale", 
    "scale/std", 
    "scale-info/std", 
    "substrate"
]
solana         = ["dep:borsh",                 "macros-proto/solana"    ]
substrate      = [                             "macros-proto/substrate" ]
cosmwasm       = ["dep:serde", "dep:schemars", "macros-proto/cosmwasm"  ]