[package]
name    = "saa-schema"
edition = { workspace = true }
authors = { workspace = true }
version = { workspace = true }

[dependencies]
macros-proto        = { path = "../macros-proto" }

# Substrate
scale               = { workspace = true, default-features = false, features = ["derive"] }
scale-info          = { workspace = true, default-features = false, features = ["derive"] }
# CosmWasm
serde               = { workspace = true, features = ["derive"] }
schemars            = { workspace = true, features = ["derive"] }
# Solana
borsh               = { workspace = true }

[features]
default        = ["borsh/derive"]
std            = ["scale/std", "scale-info/std", "substrate"]
solana         = ["macros-proto/solana", "borsh/derive"]
substrate      = ["macros-proto/substrate"]
cosmwasm       = ["macros-proto/cosmwasm"]