[package]
name    = "saa-schema"
edition = { workspace = true }
authors = { workspace = true }
version = { workspace = true }

[dependencies]
macros-proto        = { path = "../macros-proto" }

# Substrate
scale               = { workspace = true }
scale-info          = { workspace = true }
# CosmWasm
serde               = { workspace = true, features = ["derive"] }
schemars            = { workspace = true, features = ["derive"] }
# Solana
borsh               = { workspace = true, features = ["derive"] }

[features]
default        = []
substrate      = ["macros-proto/substrate"]
cosmwasm       = ["macros-proto/cosmwasm"]
solana         = ["macros-proto/solana", "borsh/derive"]