[package]
name = "smart-account-auth"
edition = { workspace = true }
authors = { workspace = true }
version = { workspace = true }

[features]
default        = []
substrate      = []
cosmwasm       = []
solana         = []


[dependencies]
saa-evm                 = { workspace = true }
saa-macros              = { workspace = true }
saa-common              = { workspace = true }