[package]
name = "smart-account-auth"
edition = { workspace = true }
authors = { workspace = true }
version = { workspace = true }


[dependencies]
saa-custom              = { workspace = true }
saa-curves              = { workspace = true }
saa-schema              = { workspace = true }
saa-common              = { workspace = true }

scale                   = { workspace = true }
scale-info              = { workspace = true }
serde                   = { workspace = true, features = ["derive"] }
schemars                = { workspace = true, features = ["derive"] }
borsh                   = { workspace = true, features = ["derive"] }


[features]
default = []
std = [
    "substrate",
    "scale/std",
    "scale-info/std",
]
solana = [
    "saa-schema/solana",
    "borsh/derive",
]
substrate      = [
    "saa-schema/substrate",
]
cosmwasm       = [
    "saa-schema/cosmwasm",
    "saa-curves/cosmwasm",
    "saa-custom/cosmwasm",
    "saa-common/cosmwasm",
]
