[package]
name = "smart-account-auth"
edition = { workspace = true }
authors = { workspace = true }
version = { workspace = true }


[dependencies]
saa-custom              = { workspace = true }
saa-curves              = { workspace = true }
saa-schema              = { workspace = true }
saa-common              = { workspace = true }

scale                   = { workspace = true }
scale-info              = { workspace = true }
serde                   = { workspace = true, features = ["derive"] }
schemars                = { workspace = true, features = ["derive"] }
borsh                   = { workspace = true, features = ["derive"] }

cosmwasm-schema         = { workspace = true }

[features]
default = []
std = [
    "saa-schema/std",
    "saa-common/std",
    "saa-custom/std",
    "scale/std",
    "scale-info/std",
    "substrate",
]
solana = [
    "saa-schema/solana",
    "saa-common/solana",
    "saa-curves/solana",
    "saa-custom/solana",
    "borsh/derive",
]
substrate = [
    "saa-schema/substrate",
    "saa-common/substrate",
    "saa-curves/substrate",
    "saa-custom/substrate",
]
cosmwasm = [
    "saa-schema/cosmwasm",
    "saa-curves/cosmwasm",
    "saa-custom/cosmwasm",
    "saa-common/cosmwasm",
]
