[package]
name    = "smart-account-auth"
edition = { workspace = true }
authors = { workspace = true }
version = { workspace = true }

[lib]
name        = "smart_account_auth"
path        = "src/lib.rs"
crate-type = ["cdylib", "rlib"]


[dependencies]
saa-custom              = { workspace = true }
saa-curves              = { workspace = true }
saa-schema              = { workspace = true }
saa-common              = { workspace = true }

scale                   = { workspace = true, optional = true, default-features = false, features = ["derive"]  }
scale-info              = { workspace = true, optional = true, default-features = false, features = ["derive"]  }

borsh                   = { workspace = true, features = ["derive"], optional = true }
schemars                = { workspace = true, features = ["derive"], optional = true }
serde                   = { workspace = true, default-features = false, features = ["derive"], optional = true }

[features]
default = []
std = [
    "saa-schema/std",
    "saa-common/std",
    "saa-custom/std",
    "saa-curves/std",
    "scale/std",
    "scale-info/std",
    "substrate",
]
solana = [
    "saa-schema/solana",
    "saa-common/solana",
    "saa-curves/solana",
    "saa-custom/solana",
    "borsh/derive",
]
substrate = [
    "dep:scale",
    "saa-schema/substrate",
    "saa-common/substrate",
    "saa-curves/substrate",
    "saa-custom/substrate",
]
cosmwasm = [
    "dep:serde",
    "dep:schemars",
    "saa-schema/cosmwasm",
    "saa-curves/cosmwasm",
    "saa-custom/cosmwasm",
    "saa-common/cosmwasm",
]