[package]
name        = "smart-account-auth"
description = "Authentication library for smart accounts on various blockchains and their virtual machines"
edition     = { workspace = true }
authors     = { workspace = true }
version     = { workspace = true }
license     = { workspace = true }
repository  = { workspace = true }


[lib]
name        = "smart_account_auth"
path        = "src/lib.rs"
crate-type = ["cdylib", "rlib"]


[dependencies]
saa-custom              = { workspace = true }
saa-curves              = { workspace = true }
saa-schema              = { workspace = true }
saa-common              = { workspace = true }

scale                   = { workspace = true, optional = true }
scale-info              = { workspace = true, optional = true }
borsh                   = { workspace = true, optional = true }
schemars                = { workspace = true }
serde                   = { workspace = true }

[features]
default = [
    "std", 
    "ethereum", 
    "cosmos", 
    "ed25519",
    "passkeys",
    "replay",
    "iterator",
]
std = [
    "scale?/std",
    "scale-info?/std",
    "saa-schema/std",
    "saa-common/std",
    "saa-custom/std",
    "saa-curves/std",
]
solana = [
    "borsh/derive",
    "saa-schema/solana",
    "saa-common/solana",
    "saa-curves/solana",
    "saa-custom/solana",
]
substrate = [
    "dep:scale",
    "dep:scale-info",
    "saa-schema/substrate",
    "saa-common/substrate",
    "saa-curves/substrate",
    "saa-custom/substrate",
]
cosmwasm = [
    "saa-curves/cosmwasm",
    "saa-custom/cosmwasm",
    "saa-common/cosmwasm",
    "wasm",
]
native = [
    "saa-curves/native",
    "saa-custom/native",
    "saa-common/native",
]
replay    = [
    "saa-common/replay",
    "saa-custom/storage",
    "storage",
]
iterator  = [
    "saa-common/iterator",
    "storage",
]
cosmwasm_2_1 = [
    "saa-custom/cosmwasm_2_1",
    "saa-curves/cosmwasm_2_1",
    "cosmwasm",
]
secretwasm  = [
    "saa-common/secretwasm",
    "saa-custom/secretwasm",
    "saa-curves/secretwasm",
    "wasm",
]
injective = [
    "saa-custom/injective",
    "saa-common/injective",
    "cosmwasm",
]
wasm      = [
    "saa-schema/cosmwasm",
]
storage   = []


# Passkey credential 
passkeys    = []

# Blockchain specific authenticators
ethereum    = []
cosmos      = []

# Enable raw curve credentials without envelops
curves      = []

# Set separately for Solana
ed25519     = []