[package]
name = "smart-account-auth"
edition = { workspace = true }
authors = { workspace = true }
version = { workspace = true }


[dependencies]
saa-custom              = { workspace = true }
saa-curves              = { workspace = true }
saa-schema              = { workspace = true }
saa-common              = { workspace = true }


[features]
default        = []
solana         = [
    "saa-schema/solana",
]
substrate      = [
    "saa-schema/substrate",
]
cosmwasm       = [
    "saa-schema/cosmwasm",
    "saa-curves/cosmwasm",
    "saa-custom/cosmwasm",
    "saa-common/cosmwasm",
]
