[package]
name = "saa-common"
edition = { workspace = true }
authors = { workspace = true }
version = { workspace = true }

[dependencies]
saa-schema          = { workspace = true }
thiserror           = { workspace = true }

bech32              = { workspace = true }
base64              = { workspace = true }

tiny-keccak         = { version = "2.0.2",  default-features = false,  features = ["keccak"] }
ripemd              = { version = "0.1.3",  default-features = false }
sha2                = { version = "0.10.8", default-features = false } 
digest              = { version = "0.10.7", default-features = false }

cosmwasm-crypto     = { version = "1.5.5", default-features = false }
ink                 = { version = "5.0.0", optional = true,  default-features = false }

cosmwasm-std        = { workspace = true, optional = true }
scale               = { workspace = true, optional = true }
scale-info          = { workspace = true, optional = true }
borsh               = { workspace = true, optional = true }
schemars            = { workspace = true }
serde               = { workspace = true }


getrandom           = { version = "0.2.15",  default-features = false, features = ["custom"] }



[features]
default     = [
    "std"
]
solana      = [
    "dep:borsh", 
    "saa-schema/solana"
]
cosmwasm    = [
    "dep:cosmwasm-std",
    "saa-schema/cosmwasm"
]
substrate   = [
    "dep:ink", 
    "dep:scale", 
    "saa-schema/substrate",
]
std         = [
    "ink?/std",
    "scale?/std",
    "scale-info?/std",
    "saa-schema/std",
]
