[package]
name = "saa-common"
description = "Common types and utilities for smart account auth"
edition = { workspace = true }
authors = { workspace = true }
version = { workspace = true }
license = { workspace = true }


[dependencies]
saa-schema          = { workspace = true }
thiserror           = { workspace = true }

bech32              = { workspace = true }
base64              = { workspace = true }

tiny-keccak         = { version = "2.0.2",  default-features = false,  features = ["keccak"] }
ripemd              = { version = "0.1.3",  default-features = false }
digest              = { version = "0.10.7", default-features = false }

cosmwasm-crypto     = { version = "1.5.5", optional = true, default-features = false }
ink                 = { version = "5.0.0", optional = true, default-features = false }

cosmwasm-std        = { workspace = true, optional = true }
cw-storage-plus     = { version = "0.16.0", optional = true }

scale               = { workspace = true, optional = true }
scale-info          = { workspace = true, optional = true }
borsh               = { workspace = true, optional = true }

sha2                = { workspace = true } 
serde               = { workspace = true }
schemars            = { workspace = true }
serde-json-wasm     = { version = "1.0.1", default-features = false }
getrandom           = { version = "0.2.15",  default-features = false, features = ["custom"] }



[features]
default     = [
    "std", "replay"
]
solana      = [
    "dep:borsh", 
    "saa-schema/solana"
]
cosmwasm    = [
    "dep:cosmwasm-std",
    "saa-schema/cosmwasm"
]
substrate   = [
    "dep:ink", 
    "dep:scale",
    "dep:scale-info",
    "saa-schema/substrate",
]
std         = [
    "ink?/std",
    "scale?/std",
    "scale-info?/std",
    "saa-schema/std",
]
native     = [
    "dep:cosmwasm-crypto",
]
replay     = [
    "storage"
]
storage    = [
    "dep:cw-storage-plus",
]
cosmos     = []
injective  = []