[package]
name = "saa-common"
edition = { workspace = true }
authors = { workspace = true }
version = { workspace = true }

[dependencies]
saa-schema          = { workspace = true }
thiserror           = { workspace = true }
hex                 = { workspace = true }

bech32              = { version = "0.9.1"  }
ripemd              = { version = "0.1.3", default-features = false }
sha2                = { version = "0.10.8" } 
tiny-keccak         = { version = "2", features = ["keccak"] }

cosmwasm-crypto     = { workspace = true }
cosmwasm-std        = { workspace = true }
cw-utils            = { workspace = true }


[features]
default     = []
std         = ["saa-schema/std", "substrate"]
solana      = ["saa-schema/solana"]
substrate   = ["saa-schema/substrate"]
cosmwasm    = ["saa-schema/cosmwasm"]