[package]
name = "saa-common"
edition = { workspace = true }
authors = { workspace = true }
version = { workspace = true }

[dependencies]
saa-schema          = { workspace = true }
thiserror           = { workspace = true }
hex                 = { workspace = true }


k256                = { workspace = true }
bech32              = { workspace = true }

base64              = { version = "0.22.1" }
tiny-keccak         = { version = "2.0.2",  default-features = false,  features = ["keccak"] }
ripemd              = { version = "0.1.3",  default-features = false }
sha2                = { version = "0.10.8", default-features = false } 
digest              = { version = "0.10.7", default-features = false }

cosmwasm-crypto     = { workspace = true }
cosmwasm-std        = { workspace = true, optional = true }
getrandom           = { workspace = true}

ink                 = { workspace = true, optional = true, default-features = false, features = []}
scale               = { workspace = true, optional = true }
scale-info          = { workspace = true, optional = true }
borsh               = { workspace = true, optional = true }
schemars            = { workspace = true }
serde               = { workspace = true }



[features]
default     = [
    "std"
]
solana      = [
    "dep:borsh", 
    "saa-schema/solana"
]
cosmwasm    = [
    "dep:cosmwasm-std",
    "saa-schema/cosmwasm"
]
substrate   = [
    "dep:ink", 
    "dep:scale", 
    "saa-schema/substrate",
]
std         = [
    "ink?/std",
    "scale?/std",
    "scale-info?/std",
    "saa-schema/std",
]
