[package]
name = "saa-common"
edition = { workspace = true }
authors = { workspace = true }
version = { workspace = true }

[dependencies]

saa-macros          = { workspace = true }
thiserror           = { workspace = true }
hex                 = { workspace = true }

bech32              = { version = "0.9.1"  }
ripemd              = { version = "0.1.3", default-features = false }
sha2                = { version = "0.10.8" } 
tiny-keccak         = { version = "2", features = ["keccak"] }

# Substrate
scale               = { workspace = true }
scale-info          = { workspace = true }

# CosmWasm
cosmwasm-std        = { workspace = true }
cosmwasm-crypto     = { workspace = true }
cw-utils            = { workspace = true }

cosmwasm-schema      = { workspace = true }
schemars             = { workspace = true }
serde                = { workspace = true }

# Solana
borsh-derive         = { workspace = true }

[features]
default     = []
substrate   = []
cosmwasm    = []

