[package]
name = "saa-common"
edition = { workspace = true }
authors = { workspace = true }
version = { workspace = true }

[dependencies]
saa-schema          = { workspace = true }
thiserror           = { workspace = true }
hex                 = { workspace = true }


ed25519             = { version = "2.2.0", default-features = false }
curve25519-dalek    = { version = "4.1.0", default-features = false, features = ["digest", "zeroize", "precomputed-tables"] }
k256                = { workspace = true }
bech32              = { workspace = true }

tiny-keccak         = { version = "2.0.2",  default-features = false,  features = ["keccak"] }
ripemd              = { version = "0.1.3",  default-features = false }
sha2                = { version = "0.10.8", default-features = false } 
digest              = { version = "0.10.7", default-features = false }

cosmwasm-std        = { workspace = true, optional = true  }

ink                 = { workspace = true, optional = true, default-features = false, features = []}
scale               = { workspace = true, optional = true }
scale-info          = { workspace = true, optional = true }
borsh               = { workspace = true, optional = true }
schemars            = { workspace = true, optional = true }
serde               = { workspace = true, optional = true }



[features]
default     = []
solana      = ["dep:borsh", "saa-schema/solana"]
cosmwasm    = [
    "dep:schemars", 
    "dep:serde", 
    "dep:cosmwasm-std",
    "saa-schema/cosmwasm"
]
std = [
    "saa-schema/std",
    "scale-info/std",
    "scale/std",
    "ink/std",
    "substrate",
]
substrate   = [
    "dep:scale", 
    "dep:ink", 
    "saa-schema/substrate",
    "ink-as-dependency"
]
ink-as-dependency = []
