[package]
name = "saa-common"
edition = { workspace = true }
authors = { workspace = true }
version = { workspace = true }

[dependencies]
saa-schema          = { workspace = true }
thiserror           = { workspace = true }
hex                 = { workspace = true }

ed25519-zebra       = { workspace = true, default-features = false }
k256                = { workspace = true }

bech32              = { version = "0.9.1"  }
ripemd              = { version = "0.1.3", default-features = false }
tiny-keccak         = { version = "2", features = ["keccak"] }
sha2                = { version = "0.10.8" } 
digest              = { workspace = true }


cosmwasm-std        = { workspace = true, optional = true  }

ink                 = { workspace = true, optional = true  }
scale               = { workspace = true, optional = true  }
scale-info          = { workspace = true, optional = true  }
borsh               = { workspace = true, features = ["derive"], optional = true }
schemars            = { workspace = true, features = ["derive"], optional = true }
serde               = { workspace = true, default-features = false, features = ["derive"], optional = true }



[features]
default     = ["std"]
solana      = ["dep:borsh", "saa-schema/solana"]
substrate   = ["dep:scale", "dep:ink", "saa-schema/substrate"]
cosmwasm    = [
    "dep:schemars", 
    "dep:serde", 
    "dep:cosmwasm-std",
    "saa-schema/cosmwasm"
]
std = [
    "dep:scale-info",
    "saa-schema/std",
    "scale/std",
    "scale-info/std",
    "ink/std",
    "substrate",
]