[package]
name        = "saa-curves"
description = "Cryptographic curves for smart account auth"
edition     = { workspace = true }
authors     = { workspace = true }
version     = { workspace = true }
license     = { workspace = true }
repository  = { workspace = true }


[dependencies]
bech32                  = { workspace = true }
saa-common              = { workspace = true }
saa-schema              = { workspace = true }

cosmwasm-std            = { workspace = true, optional = true }

scale                   = { workspace = true, optional = true  }
scale-info              = { workspace = true, optional = true  }

borsh                   = { workspace = true, optional = true }
schemars                = { workspace = true, optional = true }
serde                   = { workspace = true, optional = true }

digest                  = { version = "0.10.7", default-features = false }
p256                    = { version = "0.13.2" }


[features]
default = [
    "std"
]
solana = [
    "dep:borsh",
    "saa-schema/solana",
    "saa-common/solana",
]
substrate = [
    "dep:scale",
    "dep:scale-info",
    "saa-schema/substrate",
    "saa-common/substrate",
]
cosmwasm = [
    "dep:cosmwasm-std",
    "saa-schema/cosmwasm",
    "saa-common/cosmwasm",
    "wasm"
]
std = [
    "scale?/std",
    "scale-info?/std",
    "saa-schema/std",
    "saa-common/std",
]
native = [
    "saa-common/native",
]
cosmwasm_2_1 = [
    "cosmwasm-std/cosmwasm_2_1",
    "saa-common/cosmwasm_2_1",
    "cosmwasm",
]
secretwasm = [
    "saa-common/secretwasm",
    "wasm"
]
wasm = [
    "dep:serde",
    "dep:schemars",
    "saa-schema/cosmwasm"
]