[package]
name = "saa-curves"
edition = { workspace = true }
authors = { workspace = true }
version = { workspace = true }


[dependencies]
bech32                  = { workspace = true }
saa-common              = { workspace = true }
saa-schema              = { workspace = true }
saa-custom              = { workspace = true }

cosmwasm-std            = { workspace = true, optional = true }

scale                   = { workspace = true, optional = true  }
scale-info              = { workspace = true, optional = true  }

borsh                   = { workspace = true, optional = true }
schemars                = { workspace = true, optional = true }
serde                   = { workspace = true, optional = true }



[features]
default = [
    "std"
]
solana = [
    "dep:borsh",
    "saa-schema/solana",
    "saa-common/solana",
    "saa-custom/solana",
]
substrate = [
    "dep:scale",
    "saa-schema/substrate",
    "saa-common/substrate",
    "saa-custom/substrate",
]
cosmwasm = [
    "dep:serde",
    "dep:schemars",
    "dep:cosmwasm-std",
    "saa-schema/cosmwasm",
    "saa-custom/cosmwasm",
    "saa-common/cosmwasm",
]
std = [
    "scale?/std",
    "scale-info?/std",
    "saa-schema/std",
    "saa-common/std",
    "saa-custom/std",
]
native = [
    "saa-common/native",
    "saa-custom/native",
]