[package]
name = "saa-curves"
edition = { workspace = true }
authors = { workspace = true }
version = { workspace = true }


[dependencies]
hex                     = { workspace = true }
k256                    = { workspace = true }
bech32                  = { workspace = true }
saa-common              = { workspace = true }
saa-schema              = { workspace = true }
saa-custom              = { workspace = true }

cosmwasm-std            = { workspace = true }
cosmwasm-crypto         = { workspace = true }


[features]
default     = []
cosmwasm    = []
